apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-display-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-display
  template:
    metadata:
      labels:
        app: stats-display
    spec:
      containers:
      - name: stats-display
        image: cofedish/stats-display:kaka
        ports:
        - containerPort: 50011
---
apiVersion: v1
kind: Service
metadata:
  name: stats-display-service
spec:
  selector:
    app: stats-display
  ports:
    - protocol: TCP
      port: 50011
      targetPort: 50011

